global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Chargement des règles
rule_files: []

# Configurations de scrapping
scrape_configs:
  - job_name: "jenkins"
    metrics_path: /prometheus
    static_configs:
      - targets: ["192.168.50.4:8080"]


  - job_name: 'ubuntu'
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.50.4:9100"]

  - job_name: 'prometheus'
    static_configs:
      - targets: ["192.168.50.4:9090"]
